### ISSUE TITLE
import error in pypge.search

### ISSUE THREAD

**Issue by arendsee** [verdverm/pypge#3]
The import below

```
from pypge.search import PGE
```

outputs the following error message

```
** (pge-test.py:5235): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "./pge-test.py", line 2, in <module>
    from pypge.search import PGE
  File "/usr/lib/python3.5/site-packages/pypge/search.py", line 25, in <module>
    from websocket import create_connection
ImportError: cannot import name 'create_connection'
```

I believe the problem is that search.py is attempting to use a package that does not exist in python3. 

Replacing

```
from websocket import create_connection
```

with 

```
from websockets import connect
```

and replacing `create_connection` everywhere in search.py with `connect`, might fix the problem (I haven't looked into it very carefully yet).

**Comment by embg** [comment]
I have the same problem. I fixed it temporarily by commenting out the code that uses `create_connection`. Please fix!

**Comment by ianhbell** [comment]
My experience is that a `pip install websocket-client` fixes this particular issue

**Comment by verdverm** [comment]
Probably a missing line in requirements.txt

**Comment by verdverm** [comment]
New instructions for running in the README.md

Let me know how this works out
