### ISSUE TITLE
AttributeError: 'Model' object has no attribute ''

### ISSUE THREAD

**Issue by embg** [verdverm/pypge#6]
I got this after fixing the multi_param issue. Here's my complete console log:

```
{   'eqn_str': '0.1*exp(Abs(x)) * sin(x)',
    'name': 'Lipson_02',
    'noise': 20.0,
    'noise_type': 'percent',
    'npts': 500,
    'xs': [x],
    'xs_params': [(-9.7, 9.7)],
    'xs_str': ['x']}
Lipson_02 0.1*exp(Abs(x))*sin(x)
(1, 500)
normalized_size_score
fitness:  normalized_size_score
fitness parameters:  normalized_size_score
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
UNSIGNED FITNESS PARAMETER!!!
weights:  []
PS:  ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
xs:  [x]
funcs:  [exp, cos, sin, Abs]
func_lvl: linear
init_lvl: low
grow_lvl: low
subs_lvl: med
adds_lvl: low
muls_lvl: low
add_xtop: False
shrinker: False
limdepth: 4
[{'grow_params': {'add_extend_level': 'low',
                  'func_level': 'linear',
                  'grow_level': 'low',
                  'init_level': 'low',
                  'mul_extend_level': 'low',
                  'subs_level': 'med'},
  'pop_count': 3,
  'usable_funcs': []}]
xs:  [x]
funcs:  []
func_lvl: linear
init_lvl: low
grow_lvl: low
subs_lvl: med
adds_lvl: low
muls_lvl: low
add_xtop: False
shrinker: False
limdepth: 4
train.shape: (1, 500) (500,)
train.T.shape: (500, 1)
peekn.shape: (1, 100) (100,)



Preloop setup
mul_exprs:  5 [C/x**2, C, C*x**2, C/x, C*x]
mid_exprs:  5
add_exprs:  10
exprs_set:  15
ret_exprs 30
   -1 create first exprs      |   26                   0.07246327 seconds      0.00278705 per item
   -1 first => filtered       |   26 ->   20          0.00562501 seconds      0.00021635 per item
   -1 memoize => algebra      |   20 ->   20          0.00034261 seconds      0.00001713 per item
   -1 algebra => result models|   20 ->   13          1.47880387 seconds      0.07394019 per item
   -1 algebrad => filtered    |   13 ->   13          0.00401425 seconds      0.00030879 per item
   -1 memoized => fitting     |   13                   0.00029635 seconds      0.00002280 per item
   -1 total for fitting       |   20                   0.00003123 seconds      0.00000156 per item
         peek'n 20 2.0   .........
   -1 peeking                 |   20                   0.56771803 seconds      0.02838590 per item
   -1 peek pushing            |   20                   0.00005913 seconds      0.00000296 per item
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    pge.fit(prob['xpts'], prob['ypts'])
  File "/home/emg3/pge/code/pypge/search.py", line 282, in fit
    self.preloop()
  File "/home/emg3/pge/code/pypge/search.py", line 450, in preloop
    to_eval = self.peek_pop() + self.peek_pop() # twice the first time
  File "/home/emg3/pge/code/pypge/search.py", line 952, in peek_pop
    popped, heap = self.heap_pop(self.nsga2_peek,self.peek_count,self.fitness_calc)
  File "/home/emg3/pge/code/pypge/search.py", line 977, in heap_pop
    fitness_calc(heap_list)
  File "/home/emg3/pge/code/pypge/fitness_funcs.py", line 39, in calculator
    vs = extractor(modl)
  File "/home/emg3/pge/code/pypge/fitness_funcs.py", line 100, in extractor
    v = getattr(modl, p)
AttributeError: 'Model' object has no attribute ''
```

Here I really have no idea what to do. I'm on the develop branch.

**Comment by verdverm** [comment]
New instructions for running in the README.md

let me know how they work out

**Comment by verdverm** [comment]
This is related to #5
